FROM oven/bun:1

WORKDIR /project
RUN apt-get update -y && apt-get install -y openssl

COPY ./bun.lock ./bun.lock
COPY ./package.json ./package.json
COPY ./package-lock.json ./package-lock.json
COPY ./packages ./packages
COPY ./turbo.json ./turbo.json

COPY ./apps/backend ./apps/backend

RUN bun install
RUN bun run db:generate 

EXPOSE 3002

CMD [ "bun", "run", "start:backend" ]